function Get-MihariManagementUiHtml {
    [CmdletBinding()]
    param()

    return @'
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="color-scheme" content="light">
  <title>Mihari · Local session</title>
  <style>
    :root{--ink:#17243a;--muted:#68768a;--line:#e4eaf1;--paper:#fff;--canvas:#f3f6fa;--navy:#15243b;--blue:#2865d7;--blue2:#eaf1ff;--teal:#128577;--teal2:#e7f6f3;--amber:#9b6400;--amber2:#fff3da;--red:#b63e4d;--red2:#fff0f1;--shadow:0 10px 30px rgba(24,44,75,.06);font-family:Inter,"Segoe UI",Arial,sans-serif;color:var(--ink);background:var(--canvas)}
    *{box-sizing:border-box}body{margin:0;min-width:320px;background:var(--canvas);font-size:14px;line-height:1.45}button,input{font:inherit}button{cursor:pointer}button:disabled{opacity:.55;cursor:wait}
    .topbar{height:68px;background:var(--navy);color:#fff;display:flex;align-items:center;justify-content:space-between;padding:0 max(24px,calc((100vw - 1280px)/2));box-shadow:0 3px 14px rgba(12,29,52,.14)}
    .brand{display:flex;align-items:center;gap:12px}.logo{width:34px;height:34px;border:1px solid rgba(255,255,255,.28);border-radius:11px;display:grid;place-items:center;background:linear-gradient(145deg,#2e75e8,#18a597);box-shadow:inset 0 1px 0 rgba(255,255,255,.32)}.logo svg{width:21px;height:21px}.brand-name{font-weight:700;letter-spacing:.01em;font-size:16px}.brand-sub{font-size:11px;color:#aebbd0;letter-spacing:.11em;text-transform:uppercase;margin-top:1px}.topmeta{display:flex;align-items:center;gap:18px;color:#c8d2e1;font-size:12px}.topmeta span{display:flex;align-items:center;gap:7px}.live-dot{width:8px;height:8px;border-radius:50%;background:#32d6aa;box-shadow:0 0 0 4px rgba(50,214,170,.14)}
    main{max-width:1280px;margin:0 auto;padding:30px 24px 54px}.page-head{display:flex;justify-content:space-between;gap:24px;align-items:flex-start;margin-bottom:22px}.eyebrow{color:var(--blue);text-transform:uppercase;letter-spacing:.12em;font-size:10px;font-weight:800;margin-bottom:7px}.page-head h1{margin:0;font-size:26px;line-height:1.2;letter-spacing:-.035em}.page-head p{margin:7px 0 0;color:var(--muted);font-size:13px}.session-chip{display:flex;align-items:center;gap:10px;background:#fff;border:1px solid var(--line);border-radius:9px;padding:9px 12px;color:var(--muted);font-size:11px;box-shadow:0 2px 8px rgba(24,44,75,.025);white-space:nowrap}.session-chip strong{font-family:Consolas,"SFMono-Regular",monospace;font-size:12px;color:var(--ink);font-weight:600}
    .layout{display:grid;grid-template-columns:minmax(0,1.7fr) minmax(300px,.8fr);gap:18px;align-items:start}.stack{display:grid;gap:18px;min-width:0}.card{background:var(--paper);border:1px solid var(--line);border-radius:12px;box-shadow:var(--shadow);overflow:hidden}.card-head{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:17px 19px 14px;border-bottom:1px solid #edf0f5}.card-title{font-size:13px;font-weight:700;letter-spacing:.005em}.card-note{font-size:11px;color:var(--muted);margin-top:3px}.card-body{padding:17px 19px}.mini-label{font-size:10px;letter-spacing:.1em;text-transform:uppercase;color:var(--muted);font-weight:700}.pill{display:inline-flex;align-items:center;gap:6px;border-radius:99px;padding:5px 9px;font-size:10px;font-weight:700;letter-spacing:.025em;white-space:nowrap}.pill::before{content:"";width:6px;height:6px;border-radius:50%;background:currentColor}.pill.good{background:var(--teal2);color:var(--teal)}.pill.warn{background:var(--amber2);color:var(--amber)}.pill.bad{background:var(--red2);color:var(--red)}.pill.neutral{background:#eef2f7;color:#64738a}
    .runtime{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:11px}.runtime-tile{border:1px solid var(--line);border-radius:9px;padding:13px 14px;min-height:98px;background:linear-gradient(180deg,#fff,#fcfdff)}.runtime-top{display:flex;justify-content:space-between;align-items:center;gap:8px}.runtime-title{font-size:11px;font-weight:700;color:#536278}.runtime-icon{width:25px;height:25px;border-radius:7px;background:var(--blue2);color:var(--blue);display:grid;place-items:center}.runtime-icon svg{width:14px;height:14px}.runtime-value{font-family:Consolas,"SFMono-Regular",monospace;font-size:12px;font-weight:600;margin-top:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.runtime-meta{color:var(--muted);font-size:10px;margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
    .overview-strip{display:grid;grid-template-columns:1fr 1fr 1fr;gap:0;border-bottom:1px solid var(--line)}.overview-stat{padding:15px 19px;border-right:1px solid var(--line)}.overview-stat:last-child{border-right:0}.overview-value{font-size:18px;letter-spacing:-.035em;font-weight:700;margin-top:4px}.overview-caption{font-size:10px;color:var(--muted);margin-top:2px}
    .control-card{background:linear-gradient(145deg,#fff 25%,#f6f9ff);}.control-card .card-head{border-color:#e6ecf6}.mode-block{padding:18px 19px 17px}.mode-row{display:flex;align-items:center;justify-content:space-between;gap:16px}.mode-copy strong{display:block;font-size:13px}.mode-copy span{display:block;color:var(--muted);font-size:11px;margin-top:3px;max-width:215px}.switch{position:relative;width:48px;height:27px;flex:0 0 auto}.switch input{position:absolute;opacity:0;width:1px;height:1px}.switch-track{position:absolute;inset:0;border-radius:99px;background:#c7d0dd;transition:background .18s}.switch-track::after{content:"";position:absolute;top:3px;left:3px;width:21px;height:21px;border-radius:50%;background:#fff;box-shadow:0 1px 4px #253b5c35;transition:transform .18s}.switch input:checked+.switch-track{background:#2865d7}.switch input:checked+.switch-track::after{transform:translateX(21px)}.switch input:focus-visible+.switch-track{outline:3px solid #94b6ff;outline-offset:2px}.mode-status{display:flex;align-items:center;justify-content:space-between;margin-top:13px;padding-top:12px;border-top:1px solid var(--line);font-size:11px;color:var(--muted)}.mode-status strong{color:var(--ink)}
    .browser-action{padding:0 19px 19px}.field-label{font-size:10px;text-transform:uppercase;letter-spacing:.09em;color:var(--muted);font-weight:700;display:block;margin-bottom:6px}.url-input{width:100%;height:38px;border:1px solid #dce4ef;border-radius:7px;padding:0 10px;color:var(--ink);background:#fff;font-size:12px;outline:none}.url-input:focus{border-color:#7ca5ef;box-shadow:0 0 0 3px #dce8ff}.button{border:0;border-radius:7px;display:inline-flex;align-items:center;justify-content:center;gap:8px;height:38px;padding:0 13px;font-size:12px;font-weight:700;transition:transform .12s,background .12s}.button:active{transform:translateY(1px)}.button-primary{background:var(--blue);color:#fff;box-shadow:0 4px 10px #2865d72a}.button-primary:hover{background:#1d55c1}.button-secondary{background:#edf2fa;color:#354864}.button-secondary:hover{background:#e1e9f5}.button svg{width:15px;height:15px}.browser-action .button{width:100%;margin-top:10px}.fineprint{font-size:10px;color:var(--muted);margin:9px 1px 0;line-height:1.5}
    .details{display:grid;grid-template-columns:1fr 1fr;gap:16px}.detail{min-width:0}.detail .mini-label{margin-bottom:6px}.detail-value{font-size:12px;font-weight:600;overflow-wrap:anywhere}.detail-sub{font-size:10px;color:var(--muted);margin-top:3px;overflow-wrap:anywhere}.mono{font-family:Consolas,"SFMono-Regular",monospace}.health-row{display:flex;align-items:center;gap:7px}.health-dot{width:7px;height:7px;border-radius:50%;background:#21a58e}.health-dot.bad{background:#c34b58}.health-dot.warn{background:#d79420}
    .activity-header{display:flex;align-items:center;gap:8px}.refresh-label{font-size:10px;color:var(--muted);font-weight:500}.table-wrap{overflow:auto}.activity-table{border-collapse:collapse;width:100%;font-size:11px}.activity-table th{text-align:left;color:#8290a2;text-transform:uppercase;letter-spacing:.075em;font-size:9px;font-weight:700;padding:10px 12px;border-bottom:1px solid var(--line);white-space:nowrap}.activity-table td{padding:10px 12px;border-bottom:1px solid #f0f3f7;vertical-align:top}.activity-table tr:last-child td{border-bottom:0}.event-stage{font-weight:700;color:#40536f;white-space:nowrap}.event-target{max-width:210px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#263950}.event-outcome{font-weight:700}.event-outcome.success{color:var(--teal)}.event-outcome.failed,.event-outcome.error,.event-outcome.rejected{color:var(--red)}.event-outcome.unsupported,.event-outcome.timeout{color:var(--amber)}.event-time{white-space:nowrap;color:#758399;font-variant-numeric:tabular-nums}.empty{padding:27px 16px;text-align:center;color:#8995a5;font-size:11px}.loading{color:#8995a5}.findings-list{display:grid}.finding{padding:12px 16px;border-bottom:1px solid #f0f3f7;display:grid;grid-template-columns:26px minmax(0,1fr);gap:10px}.finding:last-child{border-bottom:0}.finding-mark{width:25px;height:25px;border-radius:7px;background:var(--amber2);color:var(--amber);display:grid;place-items:center;font-weight:800;font-size:12px}.finding-mark.red{background:var(--red2);color:var(--red)}.finding-title{font-size:11px;font-weight:700;line-height:1.4}.finding-code{font:10px Consolas,"SFMono-Regular",monospace;color:#7c899b;margin-top:3px}.finding-meta{font-size:10px;color:var(--muted);margin-top:4px;line-height:1.4}.connection-list{display:grid}.connection-row{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:12px;align-items:center;padding:11px 16px;border-bottom:1px solid #f0f3f7;font-size:11px}.connection-row:last-child{border-bottom:0}.connection-target{font-weight:600;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.connection-sub{font-size:10px;color:var(--muted);margin-top:2px}.connection-mode{font-size:9px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:#63738a;background:#f0f3f7;padding:4px 7px;border-radius:5px}.error-bar{display:none;margin-top:18px;padding:11px 14px;border:1px solid #f1ced2;background:#fff5f5;color:#91434c;border-radius:8px;font-size:11px}.error-bar.visible{display:flex;align-items:flex-start;gap:9px}.error-icon{font-weight:900}.footer{display:flex;justify-content:space-between;align-items:center;color:#8793a3;font-size:10px;margin-top:17px;padding:0 2px}.footer span{display:flex;gap:6px;align-items:center}.pulse{animation:pulse 1.8s infinite}@keyframes pulse{0%,100%{opacity:1}50%{opacity:.45}}
    @media(max-width:900px){.layout{grid-template-columns:1fr}.side{grid-row:1}.side .control-card{max-width:none}.runtime{grid-template-columns:repeat(3,minmax(0,1fr))}}
    @media(max-width:620px){.topbar{padding:0 16px;height:60px}.topmeta{gap:9px}.topmeta .hide-small{display:none}main{padding:23px 14px 38px}.page-head{display:block}.session-chip{margin-top:16px;width:max-content;max-width:100%}.runtime{grid-template-columns:1fr 1fr}.overview-stat{padding:13px}.overview-value{font-size:16px}.details{gap:13px}.activity-table th:nth-child(3),.activity-table td:nth-child(3){display:none}.card-head{padding-left:15px;padding-right:15px}.card-body{padding-left:15px;padding-right:15px}.connection-row{grid-template-columns:minmax(0,1fr) auto;gap:6px 10px}.connection-row .event-time{grid-column:1}.connection-row .connection-mode{grid-column:2;grid-row:1 / span 2}.footer{align-items:flex-start;gap:12px;flex-direction:column}}
    @media(prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.01ms!important;transition-duration:.01ms!important;scroll-behavior:auto!important}}
  </style>
</head>
<body>
  <header class="topbar">
    <div class="brand">
      <div class="logo" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none"><path d="M4 16.5 9.2 7l3.1 5.3L15 7l5 9.5M6 16.5h12" stroke="white" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"/><circle cx="9.2" cy="7" r="1.2" fill="white"/><circle cx="15" cy="7" r="1.2" fill="white"/></svg></div>
      <div><div class="brand-name">Mihari</div><div class="brand-sub">Local diagnostics</div></div>
    </div>
    <div class="topmeta"><span><i class="live-dot" id="top-live"></i><b id="top-status">Connecting</b></span><span class="hide-small">Refreshes automatically</span></div>
  </header>
  <main>
    <div class="page-head">
      <div><div class="eyebrow">Session console</div><h1>Network diagnostics</h1><p>Observe proxy activity and compare Inspect with Tunnel as you reproduce an issue.</p></div>
      <div class="session-chip"><span>SESSION</span><strong id="session-id">Loading…</strong></div>
    </div>
    <div class="layout">
      <div class="stack">
        <section class="card" aria-labelledby="overview-title">
          <div class="card-head"><div><div class="card-title" id="overview-title">Runtime overview</div><div class="card-note">Live state of this Mihari session</div></div><span class="pill neutral" id="runtime-pill">Checking</span></div>
          <div class="overview-strip">
            <div class="overview-stat"><div class="mini-label">Session mode</div><div class="overview-value" id="overview-mode">—</div><div class="overview-caption" id="overview-mode-caption">New connections use this mode</div></div>
            <div class="overview-stat"><div class="mini-label">Open connections</div><div class="overview-value" id="active-count">—</div><div class="overview-caption">Currently handled by Mihari</div></div>
            <div class="overview-stat"><div class="mini-label">Findings</div><div class="overview-value" id="finding-count">—</div><div class="overview-caption">Supported by recorded evidence</div></div>
          </div>
          <div class="card-body"><div class="runtime">
            <div class="runtime-tile"><div class="runtime-top"><span class="runtime-title">Proxy listener</span><span class="runtime-icon"><svg viewBox="0 0 20 20" fill="none"><path d="M3 5.5h14v9H3zM6 8h.01M9 8h.01M6 11h8" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></span></div><div class="runtime-value" id="proxy-endpoint">—</div><div class="runtime-meta" id="proxy-health">Waiting for listener</div></div>
            <div class="runtime-tile"><div class="runtime-top"><span class="runtime-title">Management UI</span><span class="runtime-icon"><svg viewBox="0 0 20 20" fill="none"><rect x="3" y="4" width="14" height="12" rx="1.5" stroke="currentColor" stroke-width="1.5"/><path d="M3 7h14M6 5.5h.01M8.5 5.5h.01" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg></span></div><div class="runtime-value" id="management-endpoint">—</div><div class="runtime-meta" id="management-health">Waiting for listener</div></div>
            <div class="runtime-tile"><div class="runtime-top"><span class="runtime-title">Session CA</span><span class="runtime-icon"><svg viewBox="0 0 20 20" fill="none"><path d="M10 2.8 16 5v4.7c0 3.3-2.2 5.8-6 7.5-3.8-1.7-6-4.2-6-7.5V5l6-2.2Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/><path d="m7.5 9.8 1.6 1.6 3.5-3.7" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></span></div><div class="runtime-value" id="ca-state">—</div><div class="runtime-meta" id="ca-identity">Session trust state</div></div>
          </div></div>
        </section>
        <section class="card" aria-labelledby="route-title">
          <div class="card-head"><div><div class="card-title" id="route-title">Route and trust</div><div class="card-note">What Mihari can currently determine</div></div><span class="pill neutral" id="upstream-pill">Route pending</span></div>
          <div class="card-body"><div class="details">
            <div class="detail"><div class="mini-label">Enterprise upstream</div><div class="detail-value" id="upstream-value">Resolving route…</div><div class="detail-sub" id="upstream-meta">Selected independently from the browser’s local proxy</div></div>
            <div class="detail"><div class="mini-label">Proxy listener health</div><div class="detail-value health-row"><i class="health-dot warn" id="proxy-health-dot"></i><span id="proxy-health-detail">Checking</span></div><div class="detail-sub" id="proxy-health-extra">Loopback endpoint health</div></div>
            <div class="detail"><div class="mini-label">Management listener health</div><div class="detail-value health-row"><i class="health-dot warn" id="management-health-dot"></i><span id="management-health-detail">Checking</span></div><div class="detail-sub" id="management-health-extra">Loopback endpoint health</div></div>
            <div class="detail"><div class="mini-label">Certificate identity</div><div class="detail-value" id="ca-subject">No certificate details</div><div class="detail-sub mono" id="ca-thumbprint">—</div></div>
          </div></div>
        </section>
        <section class="card" aria-labelledby="events-title">
          <div class="card-head"><div><div class="card-title" id="events-title">Recent observations</div><div class="card-note">Structured facts from the current session</div></div><div class="activity-header"><span class="pill neutral" id="event-count-pill">0 events</span><span class="refresh-label" id="last-updated">Updating…</span></div></div>
          <div class="table-wrap"><table class="activity-table"><thead><tr><th>Time</th><th>Stage</th><th>Target</th><th>Outcome</th><th>Mode</th></tr></thead><tbody id="event-rows"><tr><td colspan="5" class="empty loading">Waiting for observations…</td></tr></tbody></table></div>
        </section>
        <section class="card" aria-labelledby="connections-title">
          <div class="card-head"><div><div class="card-title" id="connections-title">Connection activity</div><div class="card-note">Active and recently accepted client connections</div></div><span class="pill neutral" id="connection-count-pill">0 recent</span></div>
          <div class="connection-list" id="connection-rows"><div class="empty">No connection activity yet</div></div>
        </section>
      </div>
      <aside class="stack side">
        <section class="card control-card" aria-labelledby="controls-title">
          <div class="card-head"><div><div class="card-title" id="controls-title">Session controls</div><div class="card-note">Changes apply to new connections</div></div><span class="pill good" id="mode-pill">INSPECT</span></div>
          <div class="mode-block">
            <div class="mode-row"><div class="mode-copy"><strong>Inspect TLS traffic</strong><span>Read HTTPS request paths using the session CA.</span></div><label class="switch" aria-label="Enable TLS inspection"><input type="checkbox" id="inspect-toggle"><span class="switch-track"></span></label></div>
            <div class="mode-status"><span>New CONNECT requests</span><strong id="mode-state">Inspect</strong></div>
          </div>
          <div class="browser-action"><label class="field-label" for="browser-url">Optional start page</label><input class="url-input" id="browser-url" type="url" placeholder="https://intranet.example/" autocomplete="url" spellcheck="false"><button class="button button-primary" id="launch-browser" type="button"><svg viewBox="0 0 20 20" fill="none"><path d="M11 3h6v6M17 3l-8 8M15 11v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h4" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Launch diagnostic Edge</span></button><p class="fineprint">Uses a dedicated temporary profile and Mihari’s HTTP/HTTPS proxy. Browser transport outside the supported diagnostic path is disabled.</p></div>
        </section>
        <section class="card" aria-labelledby="findings-title">
          <div class="card-head"><div><div class="card-title" id="findings-title">Diagnostic findings</div><div class="card-note">Conclusions backed by observed evidence</div></div></div>
          <div class="findings-list" id="finding-rows"><div class="empty">No findings available yet</div></div>
        </section>
        <section class="card" aria-labelledby="errors-title">
          <div class="card-head"><div><div class="card-title" id="errors-title">Session health</div><div class="card-note">Cleanup and runtime errors</div></div><span class="pill good" id="error-pill">Clear</span></div>
          <div class="card-body"><div class="details">
            <div class="detail"><div class="mini-label">Runtime errors</div><div class="detail-value" id="error-count">0</div></div>
            <div class="detail"><div class="mini-label">Cleanup state</div><div class="detail-value" id="cleanup-state">No cleanup errors</div></div>
          </div></div>
          <div class="error-bar" id="error-bar"><span class="error-icon">!</span><span id="error-message"></span></div>
        </section>
      </aside>
    </div>
    <div class="error-bar" id="api-error"><span class="error-icon">!</span><span id="api-error-message">Management API is not responding.</span></div>
    <div class="footer"><span><i class="live-dot" style="width:6px;height:6px;box-shadow:none"></i> Local session · Loopback only</span><span id="footer-session">Mihari diagnostic console</span></div>
  </main>
  <script>
  (function(){
    'use strict';
    var API={status:'/api/status',events:'/api/events?limit=100',findings:'/api/findings',mode:'/api/mode',browser:'/api/browser'};
    var el=function(id){return document.getElementById(id);};
    var own=function(o,k){return o!==null&&o!==undefined&&Object.prototype.hasOwnProperty.call(o,k);};
    function get(o,names){if(!o)return null;for(var i=0;i<names.length;i++){var n=names[i];if(own(o,n)&&o[n]!==null&&o[n]!==undefined)return o[n];var keys=Object.keys(o);for(var j=0;j<keys.length;j++){if(keys[j].toLowerCase()===n.toLowerCase()&&o[keys[j]]!==null&&o[keys[j]]!==undefined)return o[keys[j]];}}return null;}
    function text(v,fallback){if(v===null||v===undefined||v==='')return fallback||'—';if(typeof v==='object')return fallback||'—';return String(v);}
    function set(id,value){el(id).textContent=value;}
    function request(url,options){return fetch(url,Object.assign({credentials:'same-origin',cache:'no-store',headers:{'Accept':'application/json'}},options||{})).then(function(r){if(!r.ok)throw new Error('API returned HTTP '+r.status);return r.json();});}
    function healthInfo(value){if(value&&typeof value==='object'){var h=get(value,['healthy','isHealthy','listening','ok']);var s=get(value,['status','state','outcome','health']);return {ok:h===true||String(s).toLowerCase()==='healthy'||String(s).toLowerCase()==='running'||String(s).toLowerCase()==='listening',label:text(s,h===true?'Healthy':h===false?'Unhealthy':'Unknown'),detail:text(get(value,['message','reason','errorCode']), '')};}var t=String(value===null?'':value).toLowerCase();return {ok:value===true||t==='healthy'||t==='running'||t==='listening'||t==='true',label:text(value,'Unknown'),detail:''};}
    function endpoint(data,kind){var nested=get(data,[kind]);return text(get(data,[kind+'Endpoint',kind+'Url'])||get(nested,['endpoint','url','address']), 'Not available');}
    function routeText(route){if(route===null||route===undefined)return {main:'Route not reported',meta:'Mihari has not reported an upstream selection'};if(typeof route==='string')return {main:route,meta:''};var kind=text(get(route,['kind','routeKind','type']), 'Route');var endpointText=get(route,['endpoint','proxyEndpoint','address','host']);var source=text(get(route,['source','routeSource']), '');var reason=text(get(route,['reason','errorCode']), '');var main=kind;if(endpointText)main+=' · '+text(endpointText,'');var meta=[source,reason].filter(function(v){return v&&v!=='—';}).join(' · ');return {main:main,meta:meta};}
    function sessionData(data){return get(data,['session'])||data||{};}
    function paintStatus(data){var session=sessionData(data);var sid=text(get(data,['sessionId','id'])||get(session,['sessionId','id']), '—');var state=text(get(data,['effectiveStatus','status','runtimeStatus'])||get(session,['effectiveStatus','status','runtimeStatus']), 'Unknown');var mode=text(get(data,['mode','currentMode'])||get(session,['mode','currentMode']), 'Inspect');var inspect=get(data,['inspectEnabled','mitmEnabled']);if(inspect===null)inspect=get(session,['inspectEnabled','mitmEnabled']);if(inspect===null)inspect=String(mode).toLowerCase()==='inspect';mode=inspect?'Inspect':'Tunnel';
      var proxyH=healthInfo(get(data,['proxyHealth','proxyListenerHealth'])||get(get(data,['proxy']),['health','status','healthy']));var uiH=healthInfo(get(data,['managementHealth','uiHealth'])||get(get(data,['management']),['health','status','healthy']));
      var proxyUrl=endpoint(data,'proxy');var uiUrl=endpoint(data,'management');var ca=get(data,['ca','certificateAuthority'])||{};var caTrusted=get(ca,['trusted','isTrusted','installed']);var caEnabled=get(ca,['enabled','available']);var caState=caTrusted===true?'Trusted':caTrusted===false?'Not trusted':caEnabled===true?'Available':'Not active';
      var route=routeText(get(data,['upstreamRoute','upstream','route']));var active=get(data,['activeConnections','activeConnectionCount','connectionCount']);if(Array.isArray(active))active=active.length;
      var errors=get(data,['errors','runtimeErrors'])||[];var cleanupErrors=get(data,['cleanupErrors','cleanupError']);if(!Array.isArray(errors))errors=errors? [errors]:[];if(!Array.isArray(cleanupErrors))cleanupErrors=cleanupErrors?[cleanupErrors]:[];
      set('session-id',sid);set('footer-session','Session '+sid);set('top-status',state);set('overview-mode',mode);set('mode-state',mode);set('active-count',active===null?'—':String(active));
      var inspectToggle=el('inspect-toggle');if(document.activeElement!==inspectToggle)inspectToggle.checked=inspect;
      el('mode-pill').className='pill '+(inspect?'good':'neutral');set('mode-pill',inspect?'INSPECT':'TUNNEL');
      set('proxy-endpoint',proxyUrl);set('management-endpoint',uiUrl);set('proxy-health',proxyH.label+(proxyH.detail?' · '+proxyH.detail:''));set('management-health',uiH.label+(uiH.detail?' · '+uiH.detail:''));
      set('proxy-health-detail',proxyH.label);set('management-health-detail',uiH.label);set('proxy-health-extra',proxyH.detail||('Loopback endpoint '+(proxyH.ok?'healthy':'health check failed')));set('management-health-extra',uiH.detail||('Loopback endpoint '+(uiH.ok?'healthy':'health check failed')));
      el('proxy-health-dot').className='health-dot '+(proxyH.ok?'':'bad');el('management-health-dot').className='health-dot '+(uiH.ok?'':'bad');
      var caThumb=text(get(ca,['thumbprint','publicThumbprint']), '');var caSubject=text(get(ca,['subject','publicSubject']), '');set('ca-state',caState);set('ca-identity',caSubject|| (caThumb?'Public identity available':'Session trust state'));set('ca-subject',caSubject||'No certificate details');set('ca-thumbprint',caThumb||'—');
      var rt=routeText(get(data,['upstreamRoute','upstream','route']));set('upstream-value',rt.main);set('upstream-meta',rt.meta||'Selected independently from the browser’s local proxy');set('upstream-pill',rt.main==='Route not reported'?'Route pending':'Route observed');el('upstream-pill').className='pill '+(rt.main==='Route not reported'?'neutral':'good');
      var runtimeGood=String(state).toLowerCase()==='running'&&proxyH.ok&&uiH.ok;var runtimeBad=!proxyH.ok||!uiH.ok||String(state).toLowerCase()==='failed'||String(state).toLowerCase()==='unhealthy';el('runtime-pill').className='pill '+(runtimeGood?'good':runtimeBad?'bad':'warn');set('runtime-pill',runtimeGood?'Running':runtimeBad?'Listener issue':state);el('top-live').className='live-dot'+(runtimeGood?'':' pulse');
      set('error-count',String(errors.length));set('cleanup-state',cleanupErrors.length?'Cleanup warning':'No cleanup errors');set('error-pill',errors.length||cleanupErrors.length?'Attention':'Clear');el('error-pill').className='pill '+(errors.length||cleanupErrors.length?'warn':'good');
      var errorBar=el('error-bar');if(errors.length||cleanupErrors.length){var first=errors[0]||cleanupErrors[0];var summary=text(typeof first==='object'?get(first,['errorCode','code','message','reason']):first,'Session reported an operational error.');set('error-message',summary);errorBar.className='error-bar visible';}else{errorBar.className='error-bar';}
      el('api-error').className='error-bar';
    }
    function redactedPath(path){var p=text(path,'');var q=p.indexOf('?');if(q>=0)return p.substring(0,q)+'?[REDACTED]';return p;}
    function eventTarget(ev){var d=get(ev,['data'])||{};var host=get(d,['host','destination','authority'])||get(ev,['host']);var path=get(d,['path','urlPath']);var method=get(d,['method']);var target=text(host,'');if(method)target=text(method,'')+' ';if(host)target+=text(host,'');if(path)target+=' '+redactedPath(path);return target||'—';}
    function formatTime(value){if(!value)return '—';var d=new Date(value);if(isNaN(d.getTime()))return text(value,'—');return d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'});}
    function outcomeClass(value){var v=String(value||'').toLowerCase();if(v.indexOf('success')>=0||v==='ok'||v==='connected')return 'success';if(v.indexOf('fail')>=0||v.indexOf('error')>=0||v.indexOf('reject')>=0)return 'failed';if(v.indexOf('unsupported')>=0||v.indexOf('timeout')>=0)return 'unsupported';return '';}
    function renderEvents(payload){var events=get(payload,['events','observations','items'])||[];if(!Array.isArray(events))events=[];set('event-count-pill',events.length+' events');var tbody=el('event-rows');tbody.textContent='';if(!events.length){var empty=document.createElement('tr');var cell=document.createElement('td');cell.colSpan=5;cell.className='empty';cell.textContent='No observations yet. Launch Edge or configure a client to begin.';empty.appendChild(cell);tbody.appendChild(empty);return;}
      events.slice().reverse().slice(0,30).forEach(function(ev){var tr=document.createElement('tr');var d=get(ev,['data'])||{};var values=[formatTime(get(ev,['timestamp','time'])),text(get(ev,['stage']),'—'),eventTarget(ev),text(get(ev,['outcome']),'—'),text(get(ev,['mode']),'—')];values.forEach(function(v,i){var td=document.createElement('td');td.textContent=v;if(i===0)td.className='event-time';if(i===1)td.className='event-stage';if(i===2)td.className='event-target';if(i===3){td.className='event-outcome '+outcomeClass(v);var error=get(d,['errorCode','code']);if(error)td.title=String(error);}tr.appendChild(td);});tbody.appendChild(tr);});}
    function renderFindings(payload){var findings=get(payload,['findings','items'])||[];if(!Array.isArray(findings))findings=[];set('finding-count',String(findings.length));var root=el('finding-rows');root.textContent='';if(!findings.length){var none=document.createElement('div');none.className='empty';none.textContent='No diagnosis is supported by the observations so far.';root.appendChild(none);return;}
      findings.slice(0,12).forEach(function(f){var row=document.createElement('div');row.className='finding';var mark=document.createElement('div');mark.className='finding-mark'+(/reject|invalid|failed|error/i.test(text(get(f,['code','severity']),''))?' red':'');mark.textContent='!';var body=document.createElement('div');var title=document.createElement('div');title.className='finding-title';title.textContent=text(get(f,['summary','title','message']),text(get(f,['code']),'Diagnostic finding'));var code=document.createElement('div');code.className='finding-code';code.textContent=text(get(f,['code']),'finding');var meta=document.createElement('div');meta.className='finding-meta';var scope=text(get(f,['scope']),'');var evidence=get(f,['evidenceIds','evidence']);var count=Array.isArray(evidence)?evidence.length:0;meta.textContent=(scope?'Scope: '+scope:'')+(count?(scope?' · ':'')+count+' evidence item'+(count===1?'':'s'):'');body.appendChild(title);body.appendChild(code);body.appendChild(meta);row.appendChild(mark);row.appendChild(body);root.appendChild(row);});}
    function renderConnections(status){var items=get(status,['recentConnections','connections'])||[];if(!Array.isArray(items))items=[];set('connection-count-pill',items.length+' recent');var root=el('connection-rows');root.textContent='';if(!items.length){var empty=document.createElement('div');empty.className='empty';empty.textContent='No connection activity yet';root.appendChild(empty);return;}items.slice(0,10).forEach(function(c){var row=document.createElement('div');row.className='connection-row';var left=document.createElement('div');var target=document.createElement('div');target.className='connection-target';target.textContent=text(get(c,['host','target','authority']),text(get(c,['id','connectionId']),'Connection'));var sub=document.createElement('div');sub.className='connection-sub';sub.textContent=text(get(c,['stage','status','outcome']),'Accepted')+' · '+formatTime(get(c,['timestamp','startedAt','time']));left.appendChild(target);left.appendChild(sub);var mode=document.createElement('span');mode.className='connection-mode';mode.textContent=text(get(c,['mode']),'—');var time=document.createElement('span');time.className='event-time';time.textContent=text(get(c,['connectionId','id']),'');row.appendChild(left);row.appendChild(mode);row.appendChild(time);root.appendChild(row);});}
    var busy=false;function refresh(){if(busy)return;busy=true;var jobs=[request(API.status),request(API.events),request(API.findings)];Promise.allSettled(jobs).then(function(results){if(results[0].status==='fulfilled'){paintStatus(results[0].value);renderConnections(results[0].value);}else{el('api-error').className='error-bar visible';set('api-error-message','Management status is unavailable. '+text(results[0].reason.message,'Check the local session.'));set('top-status','Unavailable');el('top-live').className='live-dot pulse';}
        if(results[1].status==='fulfilled')renderEvents(results[1].value);if(results[2].status==='fulfilled')renderFindings(results[2].value);set('last-updated','Updated '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'}));}).finally(function(){busy=false;});}
    function post(url,body){return request(url,{method:'POST',headers:{'Accept':'application/json','Content-Type':'application/json'},body:JSON.stringify(body)});}
    el('inspect-toggle').addEventListener('change',function(){var toggle=this;toggle.disabled=true;var mode=toggle.checked?'Inspect':'Tunnel';post(API.mode,{mode:mode}).then(function(){refresh();}).catch(function(err){toggle.checked=!toggle.checked;set('api-error-message','Could not change mode. '+text(err.message,'The session may no longer be running.'));el('api-error').className='error-bar visible';}).finally(function(){toggle.disabled=false;});});
    el('launch-browser').addEventListener('click',function(){var button=this;var input=el('browser-url');var url=input.value.trim();button.disabled=true;var label=button.querySelector('span');var prior=label.textContent;label.textContent='Starting Edge…';post(API.browser,url?{url:url}:{}).then(function(result){var ok=get(result,['success','Success']);if(ok===false||get(result,['error','reason'])){throw new Error(text(get(result,['reason','error','message']),'Edge could not be started.'));}label.textContent='Edge launched';setTimeout(function(){label.textContent=prior;button.disabled=false;},1800);refresh();}).catch(function(err){label.textContent=prior;button.disabled=false;set('api-error-message','Edge launch failed. '+text(err.message,'Check browser availability and session health.'));el('api-error').className='error-bar visible';});});
    refresh();window.setInterval(refresh,2500);
  })();
  </script>
</body>
</html>
'@
}
